package rules

import com.test.schema.*;
import com.test.DroolsHelper;

dialect "java"

rule "Contact First Name is sunil"

    when
        contact:ContactType (getFirstname() == 'Sunil' )
    then
        DroolsHelper.addError(contact,"Adding contact with first name equal to Sunil");
end

rule "Contact age is invalid"

    when
        contact:ContactType (getAge() < 18 || getAge() >100 )
    then
        DroolsHelper.addError(contact,"Adding contact with age less than 18 or more than 100");
end